services:
  db:
    ports:
      - 5434:5432
    container_name: postgresql_container
    image: postgres
    environment:
      - POSTGRES_DB=first_pgdb
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
    volumes:
      - /home/essoungou_wonga/H87/christian:/var/lib/postgresql/data
    restart: always
  backend:
    build:
      dockerfile: Dockerfile
    container_name: leavemanager_container
    ports:
      - 8080:8080
    environment:
      db-url: jdbc:postgresql://localhost:5433/first_pgdb
      db-username: postgres
      db-password: 1234
    depends_on:
      - db
    restart: always